"""Gold-annotated evaluation corpus.

69 biomedical sentences with character-level span annotations spanning the
39-type schema. Format: (sentence_text, [(start, end, text, entity_type), ...]).
Copied verbatim from src/models_experiment/ner_comparison.ipynb.
"""
from __future__ import annotations

from collections import Counter

from .schema import (
    ALL_TYPES,
    TIER_1_NLP_DETECTABLE,
    TIER_2_NLP_MODERATE,
    TIER_3_NLP_HARD,
)

CORPUS = [
    ("BRCA1 and BRCA2 mutations confer a high lifetime risk of breast and ovarian cancer.",
     [(0, 5, "BRCA1", "GENE"), (10, 15, "BRCA2", "GENE"), (55, 61, "breast", "CANCER"), (66, 80, "ovarian cancer", "CANCER")]),
    ("TP53 is the most frequently mutated gene in human cancers, altered in over 50% of cases.",
     [(0, 4, "TP53", "GENE"), (58, 71, "human cancers", "DISEASE")]),
    ("EGFR amplification drives oncogenic signalling in glioblastoma multiforme.",
     [(0, 4, "EGFR", "GENE"), (46, 71, "glioblastoma multiforme", "CANCER")]),
    ("FOXO3 is associated with human longevity in multiple genome-wide association studies.",
     [(0, 5, "FOXO3", "GENE")]),
    ("The daf-2 gene encodes the C. elegans insulin/IGF-1 receptor ortholog.",
     [(4, 9, "daf-2", "GENE"), (23, 33, "C. elegans", "ORGANISM")]),
    ("mTOR complex 1 phosphorylates S6K1 and 4E-BP1 to promote cap-dependent translation.",
     [(0, 14, "mTOR complex 1", "PROTEIN"), (29, 33, "S6K1", "PROTEIN"), (38, 44, "4E-BP1", "PROTEIN")]),
    ("The p53 tumour suppressor protein is stabilised by ATM-mediated phosphorylation at Ser15.",
     [(4, 7, "p53", "PROTEIN"), (30, 37, "protein", "PROTEIN"), (52, 55, "ATM", "PROTEIN"), (83, 88, "Ser15", "SEQUENCE_VARIANT")]),
    ("SIRT1 deacetylates histone H3 at lysine 9 to silence heterochromatin.",
     [(0, 5, "SIRT1", "PROTEIN"), (19, 28, "histone H3", "PROTEIN"), (32, 41, "lysine 9", "MOLECULAR_FUNCTION")]),
    ("Rapamycin inhibits mTORC1 by binding to the FKBP12-rapamycin complex.",
     [(0, 8, "Rapamycin", "SMALL_MOLECULE"), (18, 24, "mTORC1", "PROTEIN"), (44, 69, "FKBP12-rapamycin complex", "MACROMOLECULAR_COMPLEX")]),
    ("The PRC2 complex trimethylates histone H3 at lysine 27 to repress gene expression.",
     [(4, 16, "PRC2 complex", "MACROMOLECULAR_COMPLEX"), (30, 39, "histone H3", "PROTEIN"), (43, 52, "lysine 27", "MOLECULAR_FUNCTION")]),
    ("Alternative splicing of BRAF exon 15 generates isoforms with distinct kinase activity.",
     [(24, 28, "BRAF", "GENE"), (29, 36, "exon 15", "EXON"), (39, 47, "isoforms", "TRANSCRIPT")]),
    ("The EGFR transcript variant EGFRvIII lacks exons 2-7 and is constitutively active.",
     [(4, 8, "EGFR", "GENE"), (9, 28, "transcript variant", "TRANSCRIPT"), (29, 37, "EGFRvIII", "TRANSCRIPT"), (44, 53, "exons 2-7", "EXON")]),
    ("miR-21 is upregulated in most human cancers and targets the tumour suppressor PTEN.",
     [(0, 6, "miR-21", "NON_CODING_RNA"), (40, 53, "human cancers", "DISEASE"), (79, 83, "PTEN", "GENE")]),
    ("lncRNA HOTAIR recruits PRC2 to silence HOXD genes during development.",
     [(7, 13, "HOTAIR", "NON_CODING_RNA"), (22, 26, "PRC2", "PROTEIN"), (37, 47, "HOXD genes", "GENE")]),
    ("circRNA ciRS-7 acts as a sponge for miR-7, thereby modulating EGFR expression.",
     [(8, 14, "ciRS-7", "NON_CODING_RNA"), (36, 41, "miR-7", "NON_CODING_RNA"), (62, 66, "EGFR", "GENE")]),
    ("The V600E missense mutation in BRAF constitutively activates MAPK signalling.",
     [(4, 9, "V600E", "SEQUENCE_VARIANT"), (29, 33, "BRAF", "GENE"), (59, 72, "MAPK signalling", "PATHWAY")]),
    ("rs4988235, a SNP in the LCT gene promoter, is associated with lactase persistence.",
     [(0, 9, "rs4988235", "GENOMIC_VARIANT"), (26, 29, "LCT", "GENE"), (30, 43, "gene promoter", "PROMOTER")]),
    ("APOE ε4 is the strongest common genetic risk factor for late-onset Alzheimer disease.",
     [(0, 4, "APOE", "GENE"), (5, 7, "ε4", "GENOMIC_VARIANT"), (65, 84, "Alzheimer disease", "DISEASE")]),
    ("A chromosomal translocation t(9;22) generates the BCR-ABL fusion oncogene in CML.",
     [(2, 27, "chromosomal translocation", "STRUCTURAL_VARIANT"), (28, 35, "t(9;22)", "STRUCTURAL_VARIANT"), (49, 56, "BCR-ABL", "GENE"), (75, 78, "CML", "CANCER")]),
    ("Copy number variations in the CNTN6 locus are associated with autism spectrum disorder.",
     [(0, 23, "Copy number variations", "STRUCTURAL_VARIANT"), (29, 34, "CNTN6", "GENE"), (56, 80, "autism spectrum disorder", "DISEASE")]),
    ("The MYC super-enhancer drives high-level transcription of MYC in multiple myeloma.",
     [(4, 7, "MYC", "GENE"), (8, 23, "super-enhancer", "SUPER_ENHANCER"), (57, 60, "MYC", "GENE"), (64, 80, "multiple myeloma", "CANCER")]),
    ("H3K27ac marks active enhancers and super-enhancers associated with cell identity genes.",
     [(0, 6, "H3K27ac", "EPIGENOMIC_FEATURE"), (14, 22, "enhancers", "ENHANCER"), (27, 41, "super-enhancers", "SUPER_ENHANCER")]),
    ("The TATA box is a core promoter element recognised by TBP within the pre-initiation complex.",
     [(4, 12, "TATA box", "MOTIF"), (21, 28, "promoter", "PROMOTER"), (53, 56, "TBP", "PROTEIN"), (68, 90, "pre-initiation complex", "MACROMOLECULAR_COMPLEX")]),
    ("DNA methylation at CpG islands in the CDKN2A promoter silences gene expression in cancer.",
     [(0, 15, "DNA methylation", "EPIGENOMIC_FEATURE"), (19, 30, "CpG islands", "REGULATORY_REGION"), (35, 42, "CDKN2A", "GENE"), (43, 51, "promoter", "PROMOTER"), (83, 89, "cancer", "DISEASE")]),
    ("AP-1 binding sites in the IL-6 promoter recruit FOSL1 to drive inflammatory transcription.",
     [(0, 16, "AP-1 binding sites", "TRANSCRIPTION_FACTOR_BINDING_SITE"), (24, 28, "IL-6", "GENE"), (29, 37, "promoter", "PROMOTER"), (46, 51, "FOSL1", "PROTEIN")]),
    ("Topologically associating domains (TADs) compartmentalise the genome into functional units.",
     [(0, 33, "Topologically associating domains", "TAD"), (35, 39, "TADs", "TAD")]),
    ("Hi-C data revealed a TAD boundary at the CTCF-binding site upstream of MYC.",
     [(23, 35, "TAD boundary", "TAD"), (40, 52, "CTCF-binding", "TRANSCRIPTION_FACTOR_BINDING_SITE"), (72, 75, "MYC", "GENE")]),
    ("Metformin activates AMPK by increasing the AMP:ATP ratio in hepatocytes.",
     [(0, 8, "Metformin", "SMALL_MOLECULE"), (19, 23, "AMPK", "PROTEIN"), (43, 52, "AMP:ATP", "MOLECULAR_INTERACTION"), (56, 67, "hepatocytes", "CELL_TYPE")]),
    ("Gefitinib binds the ATP-binding pocket of EGFR kinase with nanomolar affinity.",
     [(0, 9, "Gefitinib", "SMALL_MOLECULE"), (20, 50, "ATP-binding pocket of EGFR kinase", "MACROMOLECULAR_COMPLEX"), (20, 23, "ATP", "SMALL_MOLECULE")]),
    ("The SWI/SNF chromatin remodelling complex uses ATP hydrolysis to reposition nucleosomes.",
     [(4, 25, "SWI/SNF chromatin", "MACROMOLECULAR_COMPLEX"), (47, 50, "ATP", "SMALL_MOLECULE"), (51, 60, "hydrolysis", "REACTION")]),
    ("Dasatinib and quercetin act as senolytics eliminating p16-positive senescent cells.",
     [(0, 9, "Dasatinib", "SMALL_MOLECULE"), (14, 22, "quercetin", "SMALL_MOLECULE"), (31, 41, "senolytics", "SMALL_MOLECULE"), (53, 57, "p16", "PROTEIN"), (67, 82, "senescent cells", "CELL_TYPE")]),
    ("The HLA-B*57:01 haplotype predisposes carriers to abacavir hypersensitivity.",
     [(4, 17, "HLA-B*57:01", "HAPLOTYPE"), (18, 27, "haplotype", "HAPLOTYPE"), (50, 58, "abacavir", "SMALL_MOLECULE")]),
    ("Individuals homozygous for the ApoE4 genotype have a 12-fold increased Alzheimer risk.",
     [(31, 36, "ApoE4", "GENOMIC_VARIANT"), (37, 45, "genotype", "GENOTYPE"), (73, 82, "Alzheimer", "DISEASE")]),
    ("Alzheimer disease is characterised by amyloid-beta plaques and neurofibrillary tangles.",
     [(0, 18, "Alzheimer disease", "DISEASE"), (39, 55, "amyloid-beta", "PROTEIN"), (56, 63, "plaques", "PHENOTYPE"), (68, 90, "neurofibrillary tangles", "PHENOTYPE")]),
    ("Triple-negative breast cancer lacks ER, PR, and HER2 expression and has a poor prognosis.",
     [(0, 31, "Triple-negative breast cancer", "CANCER"), (39, 41, "ER", "PROTEIN"), (43, 45, "PR", "PROTEIN"), (51, 55, "HER2", "PROTEIN")]),
    ("Patients with type 2 diabetes present with polyuria, polydipsia, and hyperglycaemia.",
     [(13, 30, "type 2 diabetes", "DISEASE"), (44, 52, "polyuria", "SYMPTOM"), (54, 64, "polydipsia", "SYMPTOM"), (70, 84, "hyperglycaemia", "SYMPTOM")]),
    ("Werner syndrome is a premature ageing disorder caused by loss-of-function WRN mutations.",
     [(0, 16, "Werner syndrome", "DISEASE"), (23, 47, "premature ageing disorder", "PHENOTYPE"), (75, 78, "WRN", "GENE")]),
    ("Hutchinson-Gilford progeria syndrome accelerates cardiovascular ageing in affected children.",
     [(0, 42, "Hutchinson-Gilford progeria syndrome", "DISEASE"), (55, 78, "cardiovascular ageing", "PHENOTYPE")]),
    ("The PI3K-AKT-mTOR pathway is hyperactivated in the majority of solid tumours.",
     [(4, 18, "PI3K-AKT-mTOR", "PATHWAY"), (19, 26, "pathway", "PATHWAY"), (57, 70, "solid tumours", "CANCER")]),
    ("Phosphorylation of IκBα by IKKβ triggers its ubiquitination and proteasomal degradation.",
     [(0, 15, "Phosphorylation", "REACTION"), (19, 23, "IκBα", "PROTEIN"), (27, 31, "IKKβ", "PROTEIN"), (45, 59, "ubiquitination", "BIOLOGICAL_PROCESS"), (64, 87, "proteasomal degradation", "BIOLOGICAL_PROCESS")]),
    ("Autophagy degrades damaged organelles and misfolded proteins to maintain cellular homeostasis.",
     [(0, 9, "Autophagy", "BIOLOGICAL_PROCESS"), (29, 38, "organelles", "CELLULAR_COMPONENT"), (43, 61, "misfolded proteins", "PROTEIN"), (73, 93, "cellular homeostasis", "BIOLOGICAL_PROCESS")]),
    ("ATP hydrolysis by the vacuolar ATPase drives proton translocation across lysosomal membranes.",
     [(0, 13, "ATP hydrolysis", "REACTION"), (21, 36, "vacuolar ATPase", "PROTEIN"), (44, 63, "proton translocation", "MOLECULAR_FUNCTION"), (71, 91, "lysosomal membranes", "CELLULAR_COMPONENT")]),
    ("Wnt ligands bind Frizzled receptors to activate the beta-catenin destruction complex.",
     [(0, 12, "Wnt ligands", "SMALL_MOLECULE"), (13, 28, "Frizzled receptors", "PROTEIN"), (43, 77, "beta-catenin destruction complex", "MACROMOLECULAR_COMPLEX")]),
    ("The Notch signalling pathway regulates cell fate decisions during haematopoiesis.",
     [(4, 9, "Notch", "PATHWAY"), (10, 30, "signalling pathway", "PATHWAY"), (46, 64, "cell fate decisions", "BIOLOGICAL_PROCESS"), (72, 85, "haematopoiesis", "BIOLOGICAL_PROCESS")]),
    ("Mitochondria generate ATP via oxidative phosphorylation in their inner membrane.",
     [(0, 12, "Mitochondria", "CELLULAR_COMPONENT"), (21, 24, "ATP", "SMALL_MOLECULE"), (29, 54, "oxidative phosphorylation", "BIOLOGICAL_PROCESS"), (63, 77, "inner membrane", "CELLULAR_COMPONENT")]),
    ("Lysosomes fuse with autophagosomes to form autolysosomes, completing the autophagy pathway.",
     [(0, 9, "Lysosomes", "CELLULAR_COMPONENT"), (19, 33, "autophagosomes", "CELLULAR_COMPONENT"), (44, 57, "autolysosomes", "CELLULAR_COMPONENT"), (73, 81, "autophagy", "BIOLOGICAL_PROCESS")]),
    ("Dopaminergic neurons in the substantia nigra degenerate selectively in Parkinson disease.",
     [(0, 22, "Dopaminergic neurons", "CELL_TYPE"), (30, 45, "substantia nigra", "ANATOMY"), (72, 89, "Parkinson disease", "DISEASE")]),
    ("CD8+ cytotoxic T lymphocytes infiltrate the tumour microenvironment and kill cancer cells.",
     [(0, 28, "CD8+ cytotoxic T lymphocytes", "CELL_TYPE"), (43, 66, "tumour microenvironment", "ANATOMY"), (76, 88, "cancer cells", "CELL_TYPE")]),
    ("HeLa cells were transfected with a plasmid encoding GFP-tagged BRCA1.",
     [(0, 10, "HeLa cells", "CELL_LINE"), (63, 68, "BRCA1", "GENE")]),
    ("MCF-7 breast adenocarcinoma cells are oestrogen receptor positive.",
     [(0, 5, "MCF-7", "CELL_LINE"), (6, 30, "breast adenocarcinoma cells", "CELL_LINE"), (35, 53, "oestrogen receptor", "PROTEIN")]),
    ("Adipose tissue secretes adipokines including leptin, adiponectin, and TNF-alpha.",
     [(0, 14, "Adipose tissue", "TISSUE"), (24, 34, "adipokines", "SMALL_MOLECULE"), (45, 51, "leptin", "PROTEIN"), (53, 63, "adiponectin", "PROTEIN"), (69, 78, "TNF-alpha", "PROTEIN")]),
    ("The hippocampus undergoes progressive atrophy in Alzheimer disease.",
     [(4, 15, "hippocampus", "ANATOMY"), (36, 43, "atrophy", "PHENOTYPE"), (47, 64, "Alzheimer disease", "DISEASE")]),
    ("Pancreatic beta cells secrete insulin in response to elevated blood glucose.",
     [(0, 22, "Pancreatic beta cells", "CELL_TYPE"), (31, 38, "insulin", "PROTEIN"), (57, 70, "blood glucose", "SMALL_MOLECULE")]),
    ("NANOG and OCT4 are pluripotency factors expressed in embryonic stem cells.",
     [(0, 5, "NANOG", "PROTEIN"), (10, 14, "OCT4", "PROTEIN"), (44, 61, "embryonic stem cells", "CELL_TYPE")]),
    ("During gastrulation, WNT signalling patterns the embryonic mesoderm.",
     [(7, 20, "gastrulation", "DEVELOPMENTAL_STAGE"), (22, 25, "WNT", "GENE"), (55, 72, "embryonic mesoderm", "DEVELOPMENTAL_STAGE")]),
    ("Foetal haematopoiesis initiates in the aorta-gonad-mesonephros region.",
     [(0, 6, "Foetal", "DEVELOPMENTAL_STAGE"), (7, 22, "haematopoiesis", "BIOLOGICAL_PROCESS"), (39, 67, "aorta-gonad-mesonephros", "ANATOMY")]),
    ("Caloric restriction by 30% extended median lifespan by 40% in C57BL/6 mice.",
     [(0, 19, "Caloric restriction", "EXPERIMENTAL_FACTOR"), (62, 72, "C57BL/6", "ORGANISM"), (73, 77, "mice", "ORGANISM")]),
    ("Mice subjected to a high-fat diet for 16 weeks developed insulin resistance and hepatic steatosis.",
     [(0, 4, "Mice", "ORGANISM"), (20, 33, "high-fat diet", "EXPERIMENTAL_FACTOR"), (56, 73, "insulin resistance", "PHENOTYPE"), (78, 95, "hepatic steatosis", "PHENOTYPE")]),
    ("Intermittent fasting activated AMPK and reduced mTORC1 signalling in aged liver.",
     [(0, 21, "Intermittent fasting", "EXPERIMENTAL_FACTOR"), (32, 36, "AMPK", "PROTEIN"), (49, 55, "mTORC1", "PROTEIN"), (70, 73, "aged", "DEVELOPMENTAL_STAGE"), (74, 79, "liver", "ANATOMY")]),
    ("CTCF-mediated chromatin loops bring distal enhancers into proximity with gene promoters.",
     [(0, 4, "CTCF", "PROTEIN"), (15, 30, "chromatin loops", "THREE_D_GENOME_STRUCTURE"), (42, 50, "enhancers", "ENHANCER"), (79, 94, "gene promoters", "PROMOTER")]),
    ("Hi-C analysis revealed A/B compartment switching in senescent fibroblasts.",
     [(14, 35, "A/B compartment switching", "THREE_D_GENOME_STRUCTURE"), (39, 61, "senescent fibroblasts", "CELL_TYPE")]),
    ("Drosophila melanogaster daf-2 mutants live twice as long as wild-type flies.",
     [(0, 24, "Drosophila melanogaster", "ORGANISM"), (25, 30, "daf-2", "GENE"), (64, 69, "flies", "ORGANISM")]),
    ("Saccharomyces cerevisiae has been used to study replicative ageing and SIR2 function.",
     [(0, 24, "Saccharomyces cerevisiae", "ORGANISM"), (69, 73, "SIR2", "GENE")]),
    ("Mus musculus knockout models carrying homozygous Trp53 deletions develop tumours rapidly.",
     [(0, 11, "Mus musculus", "ORGANISM"), (49, 54, "Trp53", "GENE")]),
    ("In aged C57BL/6J mice fed a high-fat diet, rapamycin restored mTORC1-dependent autophagy "
     "and reduced senescent cell burden in adipose tissue.",
     [(3, 7, "aged", "DEVELOPMENTAL_STAGE"), (8, 16, "C57BL/6J", "ORGANISM"), (17, 21, "mice", "ORGANISM"),
      (29, 42, "high-fat diet", "EXPERIMENTAL_FACTOR"), (44, 52, "rapamycin", "SMALL_MOLECULE"),
      (62, 68, "mTORC1", "PROTEIN"), (79, 88, "autophagy", "BIOLOGICAL_PROCESS"),
      (101, 116, "senescent cell", "CELL_TYPE"), (127, 141, "adipose tissue", "TISSUE")]),
    ("CRISPR-Cas9 deletion of the PTEN tumour suppressor in prostate epithelial cells "
     "activates PI3K-AKT signalling and induces cellular senescence via p21.",
     [(0, 11, "CRISPR-Cas9", "SMALL_MOLECULE"), (27, 31, "PTEN", "GENE"), (32, 49, "tumour suppressor", "PROTEIN"),
      (53, 78, "prostate epithelial cells", "CELL_TYPE"), (89, 102, "PI3K-AKT", "PATHWAY"),
      (114, 131, "cellular senescence", "PHENOTYPE"), (136, 139, "p21", "PROTEIN")]),
    ("ChIP-seq of H3K4me3 in human embryonic stem cells revealed bivalent domains "
     "co-occupied by H3K27me3 at developmental gene promoters.",
     [(8, 15, "H3K4me3", "EPIGENOMIC_FEATURE"), (19, 45, "human embryonic stem cells", "CELL_TYPE"),
      (55, 71, "bivalent domains", "EPIGENOMIC_FEATURE"), (89, 97, "H3K27me3", "EPIGENOMIC_FEATURE"),
      (101, 118, "developmental gene", "GENE"), (119, 127, "promoters", "PROMOTER")]),
    ("The APOE ε4 haplotype increases amyloid-beta accumulation and tau phosphorylation "
     "in hippocampal neurons of aged transgenic mice.",
     [(4, 8, "APOE", "GENE"), (9, 11, "ε4", "GENOMIC_VARIANT"), (12, 20, "haplotype", "HAPLOTYPE"),
      (30, 42, "amyloid-beta", "PROTEIN"), (59, 62, "tau", "PROTEIN"),
      (93, 114, "hippocampal neurons", "CELL_TYPE"), (118, 122, "aged", "DEVELOPMENTAL_STAGE"),
      (123, 137, "transgenic mice", "ORGANISM")]),
    ("lncRNA NEAT1 scaffolds paraspeckle formation and sequesters miR-193 "
     "to upregulate MCL-1 expression in chemotherapy-resistant cancer cells.",
     [(7, 12, "NEAT1", "NON_CODING_RNA"), (22, 34, "paraspeckle", "CELLULAR_COMPONENT"),
      (52, 59, "miR-193", "NON_CODING_RNA"), (74, 79, "MCL-1", "GENE"),
      (103, 115, "cancer cells", "CELL_TYPE")]),
]


def corpus_stats() -> dict:
    type_counts = Counter(t for _, ents in CORPUS for _, _, _, t in ents)
    total_gold = sum(type_counts.values())
    t1 = sum(c for t, c in type_counts.items() if t in TIER_1_NLP_DETECTABLE)
    t2 = sum(c for t, c in type_counts.items() if t in TIER_2_NLP_MODERATE)
    t3 = sum(c for t, c in type_counts.items() if t in TIER_3_NLP_HARD)
    return {
        "n_sentences": len(CORPUS),
        "total_gold_entities": total_gold,
        "tier1_entities": t1,
        "tier2_entities": t2,
        "tier3_entities": t3,
        "n_schema_types": len([t for t in ALL_TYPES if t != "OTHER"]),
        "type_counts": dict(type_counts.most_common()),
    }
